server:
  port: 8081

spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@192.168.0.51:1521:XE
    username: HiGrocy
    password: 1234

mybatis:
  mapper-locations: classpath:mapper/*.xml
  #  default ?? ??
  type-aliases-package: com.example.springreact.mapper.*